package com.vladislav.training.platform.content.service;

/**
 * Класс {@code ContentAuditCatalog}.
 */
public final class ContentAuditCatalog {

    public static final String EVENT_TYPE_CONTENT_COURSE_DRAFT_CREATED = "CONTENT_COURSE_DRAFT_CREATED";
    public static final String EVENT_TYPE_CONTENT_COURSE_DRAFT_UPDATED = "CONTENT_COURSE_DRAFT_UPDATED";
    public static final String EVENT_TYPE_CONTENT_COURSE_PUBLISHED = "CONTENT_COURSE_PUBLISHED";
    public static final String EVENT_TYPE_CONTENT_COURSE_ARCHIVED = "CONTENT_COURSE_ARCHIVED";

    public static final String EVENT_TYPE_CONTENT_TOPIC_DRAFT_CREATED = "CONTENT_TOPIC_DRAFT_CREATED";
    public static final String EVENT_TYPE_CONTENT_TOPIC_DRAFT_UPDATED = "CONTENT_TOPIC_DRAFT_UPDATED";
    public static final String EVENT_TYPE_CONTENT_TOPIC_PUBLISHED = "CONTENT_TOPIC_PUBLISHED";
    public static final String EVENT_TYPE_CONTENT_TOPIC_ARCHIVED = "CONTENT_TOPIC_ARCHIVED";

    public static final String EVENT_TYPE_CONTENT_MATERIAL_DRAFT_CREATED = "CONTENT_MATERIAL_DRAFT_CREATED";
    public static final String EVENT_TYPE_CONTENT_MATERIAL_DRAFT_UPDATED = "CONTENT_MATERIAL_DRAFT_UPDATED";
    public static final String EVENT_TYPE_CONTENT_MATERIAL_PUBLISHED = "CONTENT_MATERIAL_PUBLISHED";
    public static final String EVENT_TYPE_CONTENT_MATERIAL_ARCHIVED = "CONTENT_MATERIAL_ARCHIVED";

    public static final String EVENT_TYPE_CONTENT_QUESTION_DRAFT_CREATED = "CONTENT_QUESTION_DRAFT_CREATED";
    public static final String EVENT_TYPE_CONTENT_QUESTION_DRAFT_UPDATED = "CONTENT_QUESTION_DRAFT_UPDATED";
    public static final String EVENT_TYPE_CONTENT_QUESTION_DRAFT_COMPOSITION_UPDATED = "CONTENT_QUESTION_DRAFT_COMPOSITION_UPDATED";
    public static final String EVENT_TYPE_CONTENT_QUESTION_PUBLISHED = "CONTENT_QUESTION_PUBLISHED";
    public static final String EVENT_TYPE_CONTENT_QUESTION_ARCHIVED = "CONTENT_QUESTION_ARCHIVED";

    public static final String EVENT_TYPE_CONTENT_TEST_DRAFT_CREATED = "CONTENT_TEST_DRAFT_CREATED";
    public static final String EVENT_TYPE_CONTENT_TEST_DRAFT_UPDATED = "CONTENT_TEST_DRAFT_UPDATED";
    public static final String EVENT_TYPE_CONTENT_TEST_DRAFT_COMPOSITION_UPDATED = "CONTENT_TEST_DRAFT_COMPOSITION_UPDATED";
    public static final String EVENT_TYPE_CONTENT_TEST_PUBLISHED = "CONTENT_TEST_PUBLISHED";
    public static final String EVENT_TYPE_CONTENT_TEST_ARCHIVED = "CONTENT_TEST_ARCHIVED";

    public static final String EVENT_TYPE_CONTENT_TOPIC_ACTIVE_FINAL_ASSIGNED = "CONTENT_TOPIC_ACTIVE_FINAL_ASSIGNED";
    public static final String EVENT_TYPE_CONTENT_TOPIC_ACTIVE_FINAL_REPLACED = "CONTENT_TOPIC_ACTIVE_FINAL_REPLACED";
    public static final String EVENT_TYPE_CONTENT_TOPIC_ACTIVE_FINAL_CLEARED = "CONTENT_TOPIC_ACTIVE_FINAL_CLEARED";

    private ContentAuditCatalog() {
    }
}
