package com.vladislav.training.platform.application.policy;

/**
 * Перечисление {@code CapabilityViolationCode}.
 */
public enum CapabilityViolationCode {
    ACTOR_UNAUTHENTICATED,
    ACTOR_CONTEXT_MISMATCH,
    ACTOR_NOT_AUTHORIZED,
    ACTOR_INACTIVE,
    USER_INACTIVE,
    USER_ALREADY_INACTIVE,
    ORG_UNIT_INACTIVE,
    TARGET_ORG_UNIT_ARCHIVED,
    NODE_KIND_NOT_ALLOWED,
    OPERATOR_HOME_UNIT_INVALID,
    OPERATOR_PRIMARY_REQUIRED,
    OPERATOR_PRIMARY_CONFLICT,
    MANAGEMENT_RELATION_NOT_ALLOWED,
    ACCESS_SCOPE_NOT_ALLOWED,
    ACCESS_AREA_NOT_ALLOWED,
    SUBTREE_SCOPE_NOT_ALLOWED,
    TEMPORARY_AUTHORITY_CONFLICT,
    HISTORY_OVERLAP,
    PERIOD_INVALID,
    REQUEST_PAYLOAD_INVALID,
    FOUNDATION_FACTS_UNAVAILABLE,
    DOWNSTREAM_OPERATION_NOT_READY,
    UNKNOWN_OPERATION,
    CAMPAIGN_TARGET_NOT_ALLOWED,
    CONTENT_PARENT_ARCHIVED,
    CONTENT_PARENT_NOT_PUBLISHED,
    CONTENT_FINAL_TEST_NOT_ELIGIBLE
}
