package com.vladislav.training.platform.application.policy;

/**
 * Перечисление {@code CapabilityTargetEntityType}.
 */
public enum CapabilityTargetEntityType {
    APP_USER,
    USER_ROLE_ASSIGNMENT,
    USER_ORGANIZATION_ASSIGNMENT,
    ORGANIZATIONAL_UNIT,
    ORGANIZATIONAL_UNIT_TYPE,
    USER_ACCESS_AREA,
    MANAGEMENT_RELATION,
    TEMPORARY_ROLE_ASSIGNMENT,
    TEMPORARY_ACCESS_AREA,
    TEMPORARY_MANAGEMENT_DELEGATION,
    COURSE,
    ASSIGNMENT_CAMPAIGN,
    ASSIGNMENT,
    ASSIGNMENT_TEST,
    TOPIC,
    MATERIAL,
    QUESTION,
    TEST,
    TOPIC_FINAL_CONTROL,
    NOTIFICATION_RULE,
    ANALYTICS_AGGREGATE,
    PERSONNEL_EXCEL_IMPORT,
    IMPORT_JOB,
    IMPORT_JOB_ITEM
}
