package com.vladislav.training.platform.access.service;

/**
 * Перечисление {@code AccessReadArea}.
 */
public enum AccessReadArea {
    USER_ADMINISTRATION,
    ORGANIZATION,
    ACCESS_MANAGEMENT,
    TEMPORARY_AUTHORITY,
    ASSIGNMENT,
    ASSIGNMENT_CAMPAIGN,
    ASSIGNED_CURRENT_ATTEMPT,
    SELF_CURRENT_ATTEMPT,
    SELF_VISIBLE_TESTING,
    SELF_RESULT_HISTORY,
    MANAGERIAL_CURRENT_SUPERVISION,
    MANAGERIAL_HISTORICAL_ANALYTICS,
    EXPERT_QUESTION_ANALYTICS,
    NOTIFICATION_ADMINISTRATION,
    NOTIFICATION_RECIPIENT_SELF,
    NOTIFICATION_RULE_ADMINISTRATION,
    IMPORT_JOB_ADMINISTRATION,
    AUDIT_EVENT_ADMINISTRATION,
    CONTENT_AUTHORING,
    CONTENT_LIFECYCLE,
    CONTENT_FINAL_CONTROL
}

