package com.vladislav.training.platform.integration.personnel.model;

/**
 * Перечисление {@code PersonnelPlannedMutationType}.
 */
public enum PersonnelPlannedMutationType {
    CREATE_USER,
    CLOSE_PRIMARY_ORG_ASSIGNMENT,
    OPEN_PRIMARY_ORG_ASSIGNMENT,
    CLOSE_ROLE_ASSIGNMENT,
    OPEN_ROLE_ASSIGNMENT,
    CLOSE_MANAGEMENT_RELATION,
    OPEN_MANAGEMENT_RELATION,
    CLOSE_USER_ACCESS_AREA,
    OPEN_USER_ACCESS_AREA,
    OPEN_TEMPORARY_ROLE_ASSIGNMENT,
    CLOSE_TEMPORARY_ROLE_ASSIGNMENT,
    OPEN_TEMPORARY_ACCESS_AREA,
    CLOSE_TEMPORARY_ACCESS_AREA,
    OPEN_TEMPORARY_MANAGEMENT_DELEGATION,
    CLOSE_TEMPORARY_MANAGEMENT_DELEGATION,
    DEACTIVATE_USER_TO_INACTIVE
}
